// 占いは創作。sourceは制作時の確認用で、画面には表示しません。
export const songs = [
  {
    "id": "canon",
    "genre": "クラシック",
    "title": "カノン ニ長調",
    "artist": "パッヘルベル / Jean-François Paillard",
    "trackId": "5P72YlVHCYzIEEKSiWGXIr",
    "background": "パッヘルベルのカノン。今回はJean-François Paillardらによる演奏です。",
    "source": "https://open.spotify.com/track/5P72YlVHCYzIEEKSiWGXIr",
    "luck": "積み重ねの吉",
    "fortune": "小さな繰り返しが、今日のあなたを支える日。急いで完成させるより、いつもの一歩を丁寧に。",
    "action": "後回しにしていたことを5分だけ進める。"
  },
  {
    "id": "moon",
    "genre": "クラシック",
    "title": "月の光",
    "artist": "ドビュッシー / Seong-Jin Cho",
    "trackId": "4VMuOvGogiPACaTyWlSMdW",
    "background": "「ベルガマスク組曲」の第3曲。演奏はSeong-Jin Choです。",
    "source": "https://open.spotify.com/track/4VMuOvGogiPACaTyWlSMdW",
    "luck": "余白の吉",
    "fortune": "月の光を思い浮かべて、今日は静かな時間を味方に。答えを急がず、自分の気持ちを聞いてみよう。",
    "action": "寝る前に画面から離れる時間を10分つくる。"
  },
  {
    "id": "love",
    "genre": "クラシック",
    "title": "愛の夢 第3番",
    "artist": "リスト / Jorge Bolet",
    "trackId": "0Ehh60Th8FiQUTv8vZBC8k",
    "background": "リストの「愛の夢」第3番、変イ長調。演奏はJorge Boletです。",
    "source": "https://open.spotify.com/track/0Ehh60Th8FiQUTv8vZBC8k",
    "luck": "やさしさの大吉",
    "fortune": "「愛の夢」という題名から届く、やさしさのおみくじ。今日は感謝を言葉にすると、自分の心にも温かさが残りそう。",
    "action": "身近な人に、具体的な「ありがとう」をひとつ伝える。"
  },
  {
    "id": "bell",
    "genre": "クラシック",
    "title": "ラ・カンパネラ",
    "artist": "リスト / Lang Lang",
    "trackId": "2Hnurh1BcigGbCGFOb4Uid",
    "background": "リストの「パガニーニ大練習曲」第3番。演奏はLang Langです。",
    "source": "https://open.spotify.com/track/2Hnurh1BcigGbCGFOb4Uid",
    "luck": "挑戦の大吉",
    "fortune": "練習曲にちなみ、今日は少し難しいことに挑む日。最初から完璧でなくても、一回試した経験が残る。",
    "action": "難しそうな課題を、最初の一手だけ試す。"
  },
  {
    "id": "gym",
    "genre": "クラシック",
    "title": "ジムノペディ 第1番",
    "artist": "サティ / Pascal Rogé",
    "trackId": "0br6kMAOk6D3eeYP5tHjlV",
    "background": "サティの「ジムノペディ」第1番。演奏はPascal Rogéです。",
    "source": "https://open.spotify.com/track/0br6kMAOk6D3eeYP5tHjlV",
    "luck": "ひと休みの吉",
    "fortune": "今日はゆっくり進むことにも価値がある日。一息ついてから戻れば、見落としていた小さな工夫に気づけるかも。",
    "action": "温かい飲み物を用意して、予定をひとつ減らす。"
  },
  {
    "id": "happy",
    "genre": "洋楽",
    "title": "Happy",
    "artist": "Pharrell Williams",
    "trackId": "60nZcImufyMA1MKQY3dcCH",
    "background": "Pharrell Williamsの楽曲「Happy」を選びました。",
    "source": "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
    "luck": "ごきげん大吉",
    "fortune": "「Happy」という題名にちなみ、小さなうれしさを拾う日。大きな成功を待たず、今ある楽しみから始めよう。",
    "action": "今日よかったことを3つメモする。"
  },
  {
    "id": "queen",
    "genre": "洋楽",
    "title": "Don't Stop Me Now",
    "artist": "Queen",
    "trackId": "7cx6hiNiJIcSNfFZYW5fsQ",
    "background": "Queenの楽曲。ここでは「Greatest Hits」収録版を選んでいます。",
    "source": "https://open.spotify.com/track/7cx6hiNiJIcSNfFZYW5fsQ",
    "luck": "前進の大吉",
    "fortune": "題名の勢いを借りて、今日は動き出してみよう。調子が出たら、その勢いをいちばん大事なことに使って。",
    "action": "やりたかったことに、まず15分取り組む。"
  },
  {
    "id": "shake",
    "genre": "洋楽",
    "title": "Shake It Off",
    "artist": "Taylor Swift",
    "trackId": "0cqRj7pUJDkTCEsJkx8snD",
    "background": "Taylor Swiftの楽曲「Shake It Off」を選びました。",
    "source": "https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD",
    "luck": "切り替えの吉",
    "fortune": "題名をヒントに、気がかりを少し手放す日。昨日の失敗を何度も採点せず、今日できることをひとつ選ぼう。",
    "action": "気になることを紙に書いてから、散歩に出る。"
  },
  {
    "id": "count",
    "genre": "洋楽",
    "title": "Count On Me",
    "artist": "Bruno Mars",
    "trackId": "3T924DFj4oJQdUKP7CYsCH",
    "background": "Bruno Marsの楽曲。ここでは「Pop Calm Down」収録版を選んでいます。",
    "source": "https://open.spotify.com/track/3T924DFj4oJQdUKP7CYsCH",
    "luck": "つながりの大吉",
    "fortune": "「頼ってね」という題名をヒントに、人とのつながりを大切にする日。一人で抱えず、頼ることから始まる会話もある。",
    "action": "誰かに小さな相談をする、または近況を聞く。"
  },
  {
    "id": "viva",
    "genre": "洋楽",
    "title": "Viva La Vida",
    "artist": "Coldplay",
    "trackId": "53tXBcrokftxjf8oNyfkYL",
    "background": "Coldplayは2008年に「Viva La Vida」を含むアルバムを発表しました。",
    "source": "https://www.coldplay.com/release/viva-la-vida/",
    "luck": "新しい一歩の吉",
    "fortune": "今日は、これまでの肩書きより「これからしたいこと」を大切に。新しい景色へ一歩だけ進む日にしよう。",
    "action": "いつもと違う道やお店をひとつ選ぶ。"
  },
  {
    "id": "lilac",
    "genre": "J-pop",
    "title": "ライラック",
    "artist": "Mrs. GREEN APPLE",
    "trackId": "78W4mTLIh4qoLu92W4IQhO",
    "background": "TVアニメ「忘却バッテリー」のオープニングテーマです。",
    "source": "https://www.youtube.com/watch?v=NH21FTlVPes",
    "luck": "青春の大吉",
    "fortune": "作品とのつながりから、今日は仲間と挑戦する日。うまくいかない瞬間も、あとで話せる思い出に変えていこう。",
    "action": "友達を誘って、何かひとつ一緒に取り組む。"
  },
  {
    "id": "blue",
    "genre": "J-pop",
    "title": "群青",
    "artist": "YOASOBI",
    "trackId": "0T4AitQuq8IJhWBWuZwkFA",
    "background": "YOASOBIが2020年9月1日に発表したシングルです。",
    "source": "https://open.spotify.com/track/0T4AitQuq8IJhWBWuZwkFA",
    "luck": "自分色の大吉",
    "fortune": "「群青」という色の名前から、今日は自分の好きを大切に。周りの正解と少し違っても、あなたらしい選択をしてみよう。",
    "action": "好きなものを、写真・文章・絵のどれかで残す。"
  },
  {
    "id": "kirari",
    "genre": "J-pop",
    "title": "きらり",
    "artist": "藤井 風",
    "trackId": "7nhXN2H8h3i2PaHPXb6FO3",
    "background": "藤井 風のシングル「きらり」。公式サイトに作品情報が掲載されています。",
    "source": "https://fujiikaze.com/music/kirari/",
    "luck": "発見の吉",
    "fortune": "題名のきらめきをヒントに、いつもの景色の中に楽しみを探す日。少し顔を上げるだけで、気分が変わるかも。",
    "action": "帰り道で、きれいだと思うものをひとつ見つける。"
  },
  {
    "id": "peace",
    "genre": "J-pop",
    "title": "ピースサイン",
    "artist": "米津玄師",
    "trackId": "364JzOajs76bJymjHm3sVY",
    "background": "米津玄師の「ピースサイン」。2017年にEPが発売されています。",
    "source": "https://open.spotify.com/intl-id/album/42FMdvus2YAtEp6hGHgiD6",
    "luck": "勇気の大吉",
    "fortune": "題名から、小さな勝利を祝うおみくじ。今日は「できなかった数」より「できた一歩」を数えて進もう。",
    "action": "一日の終わりに、頑張った自分をひとつ褒める。"
  },
  {
    "id": "cherry",
    "genre": "J-pop",
    "title": "チェリー",
    "artist": "スピッツ",
    "trackId": "2VvQRpzncrUSfnVKFBdvum",
    "background": "スピッツの「チェリー」。今回はRemastered 2002表記の音源です。",
    "source": "https://open.spotify.com/track/2VvQRpzncrUSfnVKFBdvum",
    "luck": "再会の吉",
    "fortune": "今日は懐かしいものが次の一歩のヒントになる日。昔の自分が好きだったことを、今の気持ちで楽しんでみよう。",
    "action": "久しぶりの友達に連絡する、または昔の趣味に触れる。"
  },
  {
    "id": "elise",
    "genre": "クラシック",
    "title": "エリーゼのために",
    "artist": "ベートーヴェン / Anatol Ugorski",
    "trackId": "1oMnWHBnfhkcmGVZ1iKUZn",
    "luck": "想いの吉",
    "fortune": "今日は、心に浮かんだ人を大切にする日。短い言葉でも、あなたらしい気遣いは届くはず。",
    "action": "大切な人に、ひと言メッセージを送る。",
    "source": "https://open.spotify.com/track/1oMnWHBnfhkcmGVZ1iKUZn"
  },
  {
    "id": "nocturne",
    "genre": "クラシック",
    "title": "ノクターン 第2番",
    "artist": "ショパン / Nelson Freire",
    "trackId": "7FgdNdHsetCQXksQpeGabM",
    "luck": "静けさの大吉",
    "fortune": "夜想曲をおまもりに、今日は心を整える日。静かな時間の中で、本当に大切にしたいことを見つけよう。",
    "action": "夜に5分だけ、今日の気持ちを書き出す。",
    "source": "https://open.spotify.com/track/7FgdNdHsetCQXksQpeGabM"
  },
  {
    "id": "spring",
    "genre": "クラシック",
    "title": "四季「春」第1楽章",
    "artist": "ヴィヴァルディ / Itzhak Perlman",
    "trackId": "3RUBMVfbweULyfoVMXTOLV",
    "luck": "芽吹きの大吉",
    "fortune": "春の始まりを思い浮かべて、小さな挑戦の種をまく日。すぐに結果が出なくても、始めたこと自体を喜ぼう。",
    "action": "気になっていたことを、ひとつ調べてみる。",
    "source": "https://open.spotify.com/track/3RUBMVfbweULyfoVMXTOLV"
  },
  {
    "id": "air",
    "genre": "クラシック",
    "title": "G線上のアリア",
    "artist": "バッハ / Philharmonia Virtuosi of New York",
    "trackId": "06w8P22daV4XuQ3suF1b79",
    "luck": "調和の吉",
    "fortune": "今日は自分にも人にも、少しゆとりを。相手の話を最後まで聞くことで、新しい見方が見つかりそう。",
    "action": "会話の中で、ひとつ丁寧に質問する。",
    "source": "https://open.spotify.com/track/06w8P22daV4XuQ3suF1b79"
  },
  {
    "id": "nacht",
    "genre": "クラシック",
    "title": "アイネ・クライネ・ナハトムジーク 第1楽章",
    "artist": "モーツァルト / Sir Colin Davis",
    "trackId": "4XWBXwcTdmtR4zehopVH9z",
    "luck": "軽やか大吉",
    "fortune": "今日は小さなお祝いが似合う日。いつもの時間に楽しみを足して、肩の力を抜いて進もう。",
    "action": "お気に入りのおやつで休憩する。",
    "source": "https://open.spotify.com/track/4XWBXwcTdmtR4zehopVH9z"
  },
  {
    "id": "colors",
    "genre": "洋楽",
    "title": "True Colors",
    "artist": "Zedd",
    "trackId": "2KTsF6TFius01SCYmnIkJG",
    "luck": "自分らしさの大吉",
    "fortune": "題名をヒントに、自分の色を大切にする日。誰かに合わせすぎず、好きだと思う気持ちを信じてみよう。",
    "action": "自分の好きな色を、服や小物に取り入れる。",
    "source": "https://open.spotify.com/track/2KTsF6TFius01SCYmnIkJG"
  },
  {
    "id": "wake",
    "genre": "洋楽",
    "title": "Wake Me Up",
    "artist": "Avicii",
    "trackId": "2ARTO99xVOi5L93zsxSgFb",
    "luck": "目覚めの大吉",
    "fortune": "今日は眠っていた好奇心を起こす日。知らないことに出会ったら、できるかどうかより面白そうかを考えて。",
    "action": "まだ試したことのない体験をひとつ探す。",
    "source": "https://open.spotify.com/track/2ARTO99xVOi5L93zsxSgFb"
  },
  {
    "id": "stars",
    "genre": "洋楽",
    "title": "A Sky Full of Stars",
    "artist": "Coldplay",
    "trackId": "3EDw433XoZJszPrKnfh1bB",
    "luck": "きらめきの大吉",
    "fortune": "満天の星を思い浮かべて、小さな希望を集める日。ひとつでは頼りなくても、集まれば進む方向を照らしてくれる。",
    "action": "楽しみにしている予定を3つ書く。",
    "source": "https://open.spotify.com/track/3EDw433XoZJszPrKnfh1bB"
  },
  {
    "id": "yourway",
    "genre": "洋楽",
    "title": "Just the Way You Are",
    "artist": "Bruno Mars",
    "trackId": "7BqBn9nzAq8spo5e7cZ0dJ",
    "luck": "そのままの吉",
    "fortune": "題名をヒントに、今日は今の自分を認める日。足りないものだけでなく、すでに持っている良さにも目を向けよう。",
    "action": "自分のいいところをひとつ言葉にする。",
    "source": "https://open.spotify.com/track/7BqBn9nzAq8spo5e7cZ0dJ"
  },
  {
    "id": "perfect",
    "genre": "洋楽",
    "title": "Perfect",
    "artist": "Ed Sheeran",
    "trackId": "3bABLjd9kmYt68u8pbx5jt",
    "luck": "ぬくもりの大吉",
    "fortune": "完璧な一日でなくても、大切にしたい瞬間はつくれる。今日は一緒に過ごす人や、自分の時間を丁寧に扱おう。",
    "action": "食事の時間を、少しだけゆっくり楽しむ。",
    "source": "https://open.spotify.com/track/3bABLjd9kmYt68u8pbx5jt"
  },
  {
    "id": "dance",
    "genre": "J-pop",
    "title": "ダンスホール",
    "artist": "Mrs. GREEN APPLE",
    "trackId": "1jsCice2Rjhwjyj98T2LIF",
    "luck": "楽しむ大吉",
    "fortune": "ダンスホールという題名から、今日は自分のリズムを取り戻す日。うまくやるより、楽しんでやることを選ぼう。",
    "action": "好きな曲を聴きながら、軽く体を動かす。",
    "source": "https://open.spotify.com/track/1jsCice2Rjhwjyj98T2LIF"
  },
  {
    "id": "kaiju",
    "genre": "J-pop",
    "title": "怪獣の花唄",
    "artist": "Vaundy",
    "trackId": "7dTW21YAJxnAOiUh7Rtu9S",
    "luck": "解放の大吉",
    "fortune": "今日は心の中の元気を外に出す日。遠慮していた好きなものを、少しだけ誰かに話してみよう。",
    "action": "好きな曲や作品を、友達にひとつ紹介する。",
    "source": "https://open.spotify.com/track/7dTW21YAJxnAOiUh7Rtu9S"
  },
  {
    "id": "marigold",
    "genre": "J-pop",
    "title": "マリーゴールド",
    "artist": "あいみょん",
    "trackId": "5NqGfELjcdvRIUuhgZJ34W",
    "luck": "日だまりの吉",
    "fortune": "花の名前をヒントに、身近な温かさを見つける日。何気ない会話や風景を、今日は少し長く味わってみよう。",
    "action": "外に出て、季節を感じるものを探す。",
    "source": "https://open.spotify.com/track/5NqGfELjcdvRIUuhgZJ34W"
  },
  {
    "id": "pretender",
    "genre": "J-pop",
    "title": "Pretender",
    "artist": "Official髭男dism",
    "trackId": "58dxGXavrcagRqA58fNB0Z",
    "luck": "素直さの吉",
    "fortune": "今日は無理に平気なふりをしなくていい日。自分の気持ちを認めると、次にしたいことが少し見えてきそう。",
    "action": "今の気持ちを、誰にも見せないメモに書く。",
    "source": "https://open.spotify.com/track/58dxGXavrcagRqA58fNB0Z"
  },
  {
    "id": "idol",
    "genre": "J-pop",
    "title": "アイドル",
    "artist": "YOASOBI",
    "trackId": "7ovUcF5uHTBRzUpB6ZOmvt",
    "luck": "主役の大吉",
    "fortune": "今日は自分の一日の主役になろう。人からどう見えるかより、自分が納得できる小さな選択を大切に。",
    "action": "自分のためだけの楽しみを、ひとつ予定に入れる。",
    "source": "https://open.spotify.com/track/7ovUcF5uHTBRzUpB6ZOmvt"
  }
];
